- name: Install Prometheus Tools
  package:
    name: "{{ item }}"
  with_items:
    - prometheus
    - prometheus-node-exporter

    - name: Low disk free (1GB) monitoring
  copy:
    src: file_system.yml
    dest: /etc/prometheus/file_system.yml
    mode: 0644
    owner: root
  notify: reload prometheus

- name: Provide config for Prometheus
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: 0644
    owner: root
  notify: restart prometheus

- name: Start and enable Prometheus services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - prometheus
    - prometheus-node-exporter
