---
- name: validate target_user is set.
  fail:
    message: "Missing target_user variable"
  when: target_user is not defined

- name: Get target_user home dir.
  command: 'grep -w {{ target_user }}:|cut -d":" -f6'
  register: target_user_home

- name: Install Powerline zsh, tmux and fish
  package:
    name: '{{ item }}'
  loop:
    - powerline
    - zsh
    - tmux
    - fish

- name: Update .tmuxrc to {{ target_user_home }}
  file:
    src: tmux.conf
    dst: '{{ target_user_home }}/.tmuxrc'

- name: Configure zsh
  file:
    src: zshrc
    dst: '{{ target_user_home }}/.zshrc'

- name: Create fish config dir
  file:
    ensure: dir
    path: '{{ target_user_home }}/.config/fish/completions'

- name: Get fish config
  git:
    repo: "https://github.com/evanlucas/fish-kubectl-completions.git"
    dest: '{{ target_user_home }}/.config/fish/repo'
    version: "HEAD"

- name: Symlink config
  file:
    ensure: symlink
    src: '{{ target_user_home }}/.config/fish/repo/kubectl.fish'
    path: '{{ target_user_home }}/.config/fish/completions/kubectl.fish'

