pack_name: test
github_vim_plugins:
  - user: pearofducks
    repo_name: ansible-vim
    version: 2.0
  - user: hashivim
    repo_name: vim-terraform
  - user: martinda
    repo_name: Jenkinsfile-vim-syntax
  - user: Valloric
    repo_name: YouCompleteMe
  - user: google
    repo_name: vim-jsonnet
