- name: Install package
  package:
    name: docker

- name: Configure storage driver
  copy:
    content: >
      { "storage-driver": "overlay2" }
    dest: /etc/docker/daemon.json


- name: Enable docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Add my user to docker group
  user:
    name: seb
    groups: docker
